### ISSUE TITLE
Events module is throwing error

### ISSUE THREAD

**Issue by raihanchdy** [siemens/pycontainerd#8]
Tried to get events but the module is throwing error  

    python3 -c 'import containerd.services.events.v1 ; help(containerd.services.events.v1)'
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/local/lib/python3.6/site-packages/containerd/services/events/v1/__init__.py", line 3, in <module>
    import containerd.services.events.v1.events_pb2 as eventsv1
    AttributeError: module 'containerd.services.events' has no attribute 'v1'

**Comment by thediveo** [comment]
Can you please give details about your system: what distribution do you use, which containerd package version, and how did you install the containerd package?

I just tried on an aarm64 Ubuntu 20.04.2 LTS with python 3.8.5 and containerd 1.4.1 and am successfully getting help about the services events v1 without any error.

**Comment by harjoc** [comment]
I noticed the traceback mentioned above on ubuntu18.04 with any containerd pypi release, and python 3.6. The example that imports containerd.services.containers works, and it's probably because containers/v1/__init__.py is empty while events/v1/__init__.py is not.
The events example does work on ubuntu 20.04.

**Comment by thediveo** [comment]
hmm, could the the corner case described in https://stackoverflow.com/a/24968941

**Comment by thediveo** [comment]
I was able to reproduce the error with a Python 3.6 venv on my Ubuntu 20.04 LTS. The fix is in fact as suggested in the SO answer mentioned above to not use the `import ... as ...` form in this corner case, but instead `from ... import ... as ...`. For a quick test I simply edited the installed site package in place, `site-packages/containerd/services/events/v1/__init__.py` in particular and replacing the failing import as follows:

```
#import containerd.services.events.v1.events_pb2 as eventsv1                                                                                                       
from containerd.services.events.v1 import events_pb2 as eventsv1
```

**Comment by raihanchdy** [comment]
Tried the workaround and its working.

The events giving container ids with which is very difficult to track the container activity when you have more than 100 containers.
Can you please add the feature to get container names and also the whole output in a single json.

Also can you please update the document with all the use cases of the module. If I want to get container stats then how to use the module.

**Comment by thediveo** [comment]
@raihanchdy please do not put feature requests into an originally bug report, this complicates things and issues can never become done.

The scope for this Python package is to provide access to containerd's GRPC API. I'm afraid, we don't have the resources to work on it other than the occasional fix and API version update. Making the rather low-level containerd API more pleasant is unfortunately completely out of scope for this project and best done in new and independent projects.

Of course, we'll be thankful for PRs adding more examples, especially for those use cases we didn't tackle in our own projects so far.

As Silvano merged the fix PR and the above described "hotfix" also works for you until we manage to rwlwase an updated PyPi package I think we can close this issue as resolved for the original crash.

**Comment by Silvanoc** [comment]
@raihanchdy do you agree with @TheDiveO ? Can we close this issue?

**Comment by thediveo** [comment]
@Silvanoc I think we can close this issue, as there has been no feedback.
